name: fixedconv
channels:
  - defaults
  - conda-forge
  - pytorch
  - fastai
dependencies:
  # basics
  - python 3.7.*
  - pip
  - numpy
  - scipy
  - jupyter
  
  # visual
  - matplotlib
  
  # DL libraries
  - pytorch
  - torchvision
  - fastai
